[package]
name = "firework_lang"
version = "0.1.2"
edition = "2018"
authors = ["Pavlos-Efstathiou"]


[dependencies]
rustyline = "9.0.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lexer"
harness = false