[package]
name = "firework_lang"
version = "0.2.0"
edition = "2021"
authors = ["Pavlos-Efstathiou"]
description = "Firework Programming Language"

[dependencies]
pest = "2"
pest_derive = "2"
clap = "2"
indoc = "1"
toml = "0.5"