[package]
name = "firework_lang"
version = "0.2.1"
edition = "2021"
authors = ["Pavlos-Efstathiou"]
description = "Firework Programming Language"
license = "GPL-3.0"
repository = "https://github.com/Pavlos-Efstathiou/firework_lang"
readme = "README.md"
keywords = ["programming-language", "firework"]

[dependencies]
pest = "2"
pest_derive = "2"
clap = "2"
indoc = "1"
toml = "0.5"